### ISSUE TITLE
Duplicate posts

### ISSUE THREAD

**Issue by xuebofan** [saadmanrafat/imgur-scraper#10]
Hi, I am a user who is using your script. I think there exists a potential bug where a single album_id might be displayed in two different dates (i.e. "2019.05.17/C1PSBVl" and "2019.05.18/C1PSBVl", which are both returned). Please help to fix this. Thanks!

**Comment by saadmanrafat** [comment]
Thanks for the bug report. However, a bit more context would make the debugging process easier. To start `imgur-scraper` doesn't currently return `album_id` or `date` for that matter. `Date` of specific posts will be available in the next release.
