### ISSUE TITLE
Upload newest version to pypi

### ISSUE THREAD

**Issue by tonimelisma** [saadmanrafat/imgur-scraper#14]
There's been interesting updates to imgur-scraper yet these are only in GitHub. Can you please upload the newest version also to pypi?

**Comment by saadmanrafat** [comment]
I would be happy to merge a pull request that updates the README.md page that reflects the changes? Then I can publish the project on PyPI. Thanks!

**Comment by tonimelisma** [comment]
I'm sorry, but you're asking for someone to create a PR to update the readme..? Is it because you are too busy yourself?

**Comment by saadmanrafat** [comment]
@tonimelisma yeah I actually am. But if someone volunteers to write the README.md. I'm more than happy to merge the pull request and release the latest version on PyPI.

**Comment by saadmanrafat** [comment]
Can you please not close unresolved issues? You can subscribe from this thread. This you are receiving unwanted notifications. 

Thanks!

**Comment by tonimelisma** [comment]
Ok. It was an issue I opened, you asked me to fix it and I won't, so I thought it's most logical to close it.

It's just looking at this project I can't with a good heart help here. You've already got two significant external contributions to your project, one merged and one open PR, which you haven't published for other people to enjoy as you're too busy.

Yet you haven't been too busy to update your PayPal information for potential donations?

I know maintaining any open source projects is a pretty thankless job and I'm grateful for all the contributions you've made. In this case the behaviour just goes too much against my values.

**Comment by saadmanrafat** [comment]
I've been maintaining and contributing to this library for three years and have plans to ensure its stability and longevity. However, I'm outraged by your remarks that I'm benefiting personally from other people's donations. I **have not received any donation** for the development or maintainence of [imgur-scraper](https://github.com/saadmanrafat/imgur-scraper). The donation link was shortly removed. And I moved on to other things. 

The unmerged PR requests you are referring to #7 is a duplication of PR requests made on Oct 3, 2019 #6, which was merged. The changes weren't properly documented on the README.md. So the decision was made not to publish on PyPI. That's part of what open-source maintainers do -- keep the project **stable**. And not vaguely publish undocumented, untested code on PyPI. As long as I maintain this project, users downloading the `imgur-scraper` through PIP will find a stable release with proper documentation. I personally feel that I owe it to them.
  
Furthermore, the project is licensed under the MIT License. **Which assumes no liability or warranty on my part**. And the generous people who issued quality PR requests to the project knew this and I thanked them for it.  Also, MIT License also permits anyone to use this repository however they choose. You can use it commercially, modify and distribute the code or even use it privately. 

Anyone has the right to fork the project and update the documentation and release and maintain it as their own on PyPI.
