### ISSUE TITLE
Error: Dict contains fields not in fieldnames: 'likes', 'dislikes'

### ISSUE THREAD

**Issue by saadmanrafat** [saadmanrafat/imgur-scraper#16]
**Describe the bug**

**To Reproduce**
```
$ imgur-scraper --date 2018-12-25 --end_date 2020-12-30 --csv --details
Grabbing The most viral images from Tuesday, Dec 25 2018
dict contains fields not in fieldnames: 'likes', 'dislikes'

```
**Desktop**
 - OS: Ubuntu 20.04.2 LTS 

**Additional context**
Only effects version v2.6.2

**Comment by Alireza-Sampour** [comment]
May I work on this?

**Comment by saadmanrafat** [comment]
> May I work on this?

Thank you for your reply. Yes, please. But I fixed the issue. It was a simple dictionary issue. But please do feel free to contribute in any way. I don't have unit tests yet. That would be a great place to help the tool.

Thanks
