### ISSUE TITLE
Scrape the time of the post 

### ISSUE THREAD

**Issue by saadmanrafat** [saadmanrafat/imgur-scraper#4]
Right now imgur-scraper scrapers 7-8 years of imgur data with 500 viral data points from each day. Unfortunately, we are missing the **time** of the post. The scraped time should be converted  UTC time. 

Attributes we are scraping now. 
```
{
  'title': 'I said no, my fiancé said yes. Meet Zeta', 
  'url': 'https://imgur.com/gallery/H5Xw4dh', 
  'points': '5,996', 
  'tags': 'aww,kitten,kitty', 
  'type': 'image', 
  'views': '4,363'
}
```

**Comment by oknotok97** [comment]
Hi, Nice project you have here! I take this issue :)

**Comment by saadmanrafat** [comment]
great! I'll assign you to it then! 

happy hacking!
