### ISSUE TITLE
Extraction of more features of a post

### ISSUE THREAD

**Issue by gaurav-kay** [saadmanrafat/imgur-scraper#5]
If there is a need to extract more data like the author, upvotes etc. I'd like to help!
@saadmanrafat

**Comment by saadmanrafat** [comment]
Thank you for your interest @gaurav-kay. We would like your help too. We try to extract information data scientists can use. We don't yet scrape the number of comments or the operating system used to publish the post. Here's an example of a [post](https://imgur.com/gallery/AIvGnRA) that shows it was upload from Android. 

We also lack [unittests](https://docs.python.org/3.6/library/unittest.html), which could make sure that the existing features are working perfectly. 

You can choose to contribute to any of the above. I'm also open to suggestions!

**Comment by gaurav-kay** [comment]
Sure thing!
